### ISSUE TITLE
MultiBlockChange not working in 1.16.2

### ISSUE THREAD

**Issue by GBroad** [dmulloy2/ProtocolLib#956]
**Describe the bug**
MultiBlockChange not supported in Protocollib 1.16.2

**To Reproduce**
Initialise MultiBlockChange Protocollib class

**Expected behavior**
The class will not load, it should load.

**Screenshots**
![image](https://user-images.githubusercontent.com/33567083/91629602-417f2400-e9c2-11ea-829c-fa75ca5faa65.png)
Caused by: java.lang.RuntimeException: Unable to find MultiBlockChangeInfo (PacketPlayOutMultiBlockChange$MultiBlockChangeInfo)
java.lang.NoClassDefFoundError: Could not initialize class com.comphenix.protocol.wrappers.MultiBlockChangeInfo

**Version Info**
https://pastebin.com/LbU8TfM4

**Additional context**
NMS class fails to resolve.
![image](https://user-images.githubusercontent.com/33567083/91629636-9884f900-e9c2-11ea-8503-8866cde99356.png)
MultiBlockChange is no longer a class

**Comment by joehot200** [comment]
From dmulloy2: 

> MultiBlockChangeInfo was removed in 1.16.2, see here for the new format: #949

**Comment by GBroad** [comment]
> From dmulloy2:
> 
> > MultiBlockChangeInfo was removed in 1.16.2, see here for the new format: #949

Given the information in the packet is essentially the same (from my brief glance), would it not be a good idea to let multiblockchange continue to work for backwards compatibility with older plugins?

**Comment by joehot200** [comment]
I think the most significant difference is that the new packet changes a 16x16x16 area. The old one changed a 16x256x16 area.

If it helps, I just wrote a guide on the new block change at https://www.spigotmc.org/threads/new-1-16-2-multiblockchange-protocollib.461832/
