### ISSUE TITLE
Searching for IBlockData on 1.7 Spigot

### ISSUE THREAD

**Issue by Exloki** [dmulloy2/ProtocolLib#199]
When using ProtocolLib 3.6.5, 3.6.6 or 3.7 I encounter "NoClassDefFoundError: Could not initialize class com.comphenix.protocol.wrappers.WrappedBlockData" while trying to send a player a multi block change packet; this appears to be caused by the static initialisers trying to find the NMS class for IBlockData but the NMS package 1_7_R4 doesn't contain this class; thus this error occurs.

Code sample where the error occurs (line 11) - https://gist.github.com/Exloki/1cea912ee8e924cf13eeb3bf0fcaef8d

/protocol dump - http://pastebin.com/68L7ECMX

**Comment by dmulloy2** [comment]
Most of that code won't work in 1.7 because it was designed for 1.8 and up. 1.7 is almost 2 years old and is two major versions obsolete, so it is no longer supported.

**Comment by Exloki** [comment]
Even when using version YOU state are ready & working with 1.7 on your Spigot & Bukkit page? Might as well just drop that message on your pages if you the code doesn't work and you refuse to offer support.

Sounds like you shouldn't have released a broken 1.7 version honestly.

**Comment by dmulloy2** [comment]
The versions themselves are working, but not the version-specific APIs. Sounds like you shouldn't be using an obsolete server version honestly.
