### PR TITLE
Update to 1.19.4

### LINKED ISSUE #2233: 1.19.4
- [x] This issue is not solved in a development build

**Describe the bug**
PL doesn't work properly on latest Paper 1.19.4 build.

**To Reproduce**
Listen to `PacketType.Status.Server.SERVER_INFO` and use `event.getPacket().getServerPings().read(0);` inside `onPacketSending`.
It was worked fine in 1.19.3.

**Expected behavior**
Everything works

**Version Info**
```
ProtocolLib version 5.0.0-SNAPSHOT-b614
This server is running Paper version git-Paper-"fe88107" (MC: 1.19.4, Git: fe88107 on dev/1.19.4)
```

**Additional context**
```
[2023-03-16 14:35:58 | Netty Server IO #1] [DT] Unhandled exception occurred in onPacketSending(PacketEvent) for DT
java.lang.NoClassDefFoundError: Could not initialize class com.comphenix.protocol.wrappers.WrappedServerPing
	at com.comphenix.protocol.wrappers.Converters$3.getSpecific(Converters.java:103) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.wrappers.Converters$1.getSpecific(Converters.java:50) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.reflect.StructureModifier.readInternal(StructureModifier.java:301) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.reflect.StructureModifier.read(StructureModifier.java:251) ~[ProtocolLib.jar:?]
	at test.plugin.dt.HideAP.onPacketSending(HideAP.java:35) ~[DT.jar:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.PacketFilterManager.postPacketToListeners(PacketFilterManager.java:547) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:521) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.netty.manager.NetworkManagerInjector.onPacketSending(NetworkManagerInjector.java:99) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector.processOutbound(NettyChannelInjector.java:571) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.processPacketOutbound(NettyChannelProxy.java:266) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.writeAndFlush(NettyChannelProxy.java:223) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.writeAndFlush(NettyChannelProxy.java:233) ~[ProtocolLib.jar:?]
	at net.minecraft.network.Connection.doSendPacket(Connection.java:466) ~[?:?]
	at net.minecraft.network.Connection.sendPacket(Connection.java:428) ~[?:?]
	at net.minecraft.network.Connection.send(Connection.java:382) ~[?:?]
	at net.minecraft.network.Connection.send(Connection.java:368) ~[?:?]
	at com.destroystokyo.paper.network.StandardPaperServerListPingEventImpl.processRequest(StandardPaperServerListPingEventImpl.java:113) ~[paper-1.19.4.jar:?]
	at net.minecraft.server.network.ServerStatusPacketListenerImpl.handleStatusRequest(ServerStatusPacketListenerImpl.java:156) ~[?:?]
	at net.minecraft.network.protocol.status.ServerboundStatusRequestPacket.handle(ServerboundStatusRequestPacket.java:19) ~[?:?]
	at net.minecraft.network.protocol.status.ServerboundStatusRequestPacket.handle(ServerboundStatusRequestPacket.java:8) ~[?:?]
	at net.minecraft.network.Connection.genericsFtw(Connection.java:314) ~[?:?]
	at net.minecraft.network.Connection.channelRead0(Connection.java:298) ~[?:?]
	at net.minecraft.network.Connection.channelRead0(Connection.java:53) ~[?:?]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[netty-codec-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at com.comphenix.protocol.injector.netty.channel.InboundPacketInterceptor.channelRead(InboundPacketInterceptor.java:28) ~[ProtocolLib.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346) ~[netty-codec-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318) ~[netty-codec-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346) ~[netty-codec-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318) ~[netty-codec-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at net.minecraft.server.network.LegacyQueryHandler.channelRead(LegacyQueryHandler.java:122) ~[?:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[netty-handler-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.handler.flush.FlushConsolidationHandler.channelRead(FlushConsolidationHandler.java:152) ~[netty-handler-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.87.Final.jar:4.1.87.Final]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[2023-03-16 14:35:58 | Netty Server IO #1] Parameters: 
  net.minecraft.network.protocol.status.PacketStatusOutServerInfo@5478f3ac[
    a=ServerPing[description=io.papermc.paper.adventure.AdventureComponent@2e81568, players=Optional[ServerPingPlayerSample[max=32, online=0, sample=[]]], version=Optional[ServerData[name=Paper 1.19.4, protocol=762]], favicon=Optional[a[iconBytes=[B@25bdc35a]], enforcesSecureChat=false]
  ]
```

### PR DESCRIPTION
**Pull request by dawon**
This is an initial take on the update to 1.19.4.

Feedback welcome!

Would close #2233

Todo:
- [ ] rework WrappedServerPing - original class was reworked to a record
- [x] add missing new packets

### CODE REVIEW

File: src/main/java/com/comphenix/protocol/utility/MinecraftVersion.java [hunk 1]
```diff
@@ -40,7 +40,7 @@ public final class MinecraftVersion implements Comparable<MinecraftVersion>, Ser
 	/**
 	 * Version 1.19.3 - introducing feature preview
 	 */
-	public static final MinecraftVersion FEATURE_PREVIEW_UPDATE = new MinecraftVersion("1.19.3");
+	public static final MinecraftVersion FEATURE_PREVIEW_UPDATE = new MinecraftVersion("1.19.4");
```
Comment (derklaro) [inline src/main/java/com/comphenix/protocol/utility/MinecraftVersion.java:43]: Not sure if you should change this one, 1.19.3 introduced some new features related to packets and people might use this constant to check if they should enable them

Comment (derklaro) [reply src/main/java/com/comphenix/protocol/utility/MinecraftVersion.java:43]: For example here: 
https://github.com/juliarn/NPC-Lib/blob/db1a4fd803c09b31c2c46cc92720f572d85d84ef/bukkit/src/main/java/com/github/juliarn/npclib/bukkit/protocol/ProtocolLibPacketAdapter.java#L304-L315

Comment (dawon) [reply src/main/java/com/comphenix/protocol/utility/MinecraftVersion.java:43]: Yes, I realized it later and have it reverted locally... I am now still thinking about how to rework the WrappedServerPing, because as a record it is immutable while the old one was mutable... I am a bit afraid that it will be a breaking change...

**Comment by romanalexander** [comment]
I tried this PR. For some reason `SPAWN_ENTITY` listener doesn't work.

/protocol dump
https://gist.github.com/romanalexander/cf77effa4807f82b094909b90113fcb9

Logs from listening to all send/receive packets:
```
[21:39:35] [Server thread/INFO]: Server command: /mob chicken
[21:39:35] [Server thread/INFO]: onPacketSending: PacketContainer[type=SYSTEM_CHAT[class=ClientboundSystemChatPacket, id=100], structureModifier=StructureModifier[fieldType=class java.lang.Object, data=[com.comphenix.protocol.reflect.accessors.DefaultFieldAccessor@2410924c, com.comphenix.protocol.reflect.accessors.DefaultFieldAccessor@76c92133, com.comphenix.protocol.reflect.accessors.DefaultFieldAccessor@45615e23]]]
[21:39:35] [Server thread/INFO]: onPacketSending: PacketContainer[type=REL_ENTITY_MOVE[class=PacketPlayOutRelEntityMove, id=43], structureModifier=StructureModifier[fieldType=class java.lang.Object, data=[com.comphenix.protocol.reflect.accessors.DefaultFieldAccessor@6ae4ebe9, com.comphenix.protocol.reflect.accessors.DefaultFieldAccessor@25bb20d0, com.comphenix.protocol.reflect.accessors.DefaultFieldAccessor@1f0e8500, com.comphenix.protocol.reflect.accessors.DefaultFieldAccessor@16dad329, com.comphenix.protocol.reflect.accessors.DefaultFieldAccessor@5bacc9b8, com.comphenix.protocol.reflect.accessors.DefaultFieldAccessor@27edcfbd, com.comphenix.protocol.reflect.accessors.DefaultFieldAccessor@4c2068c5, com.comphenix.protocol.reflect.accessors.DefaultFieldAccessor@ca3a9f3, com.comphenix.protocol.reflect.accessors.DefaultFieldAccessor@31ff40d6]]]
[21:39:35] [Server thread/INFO]: onPacketSending: PacketContainer[type=ENTITY_METADATA[class=PacketPlayOutEntityMetadata, id=82], structureModifier=StructureModifier[fieldType=class java.lang.Object, data=[com.comphenix.protocol.reflect.accessors.DefaultFieldAccessor@7826e173, com.comphenix.protocol.reflect.accessors.DefaultFieldAccessor@378fd8f2]]]
[21:39:35] [Server thread/INFO]: onPacketSending: PacketContainer[type=UPDATE_ATTRIBUTES[class=PacketPlayOutUpdateAttributes, id=106], structureModifier=StructureModifier[fieldType=class java.lang.Object, data=[com.comphenix.protocol.reflect.accessors.DefaultFieldAccessor@267203c1, com.comphenix.protocol.reflect.accessors.DefaultFieldAccessor@6dc00e29]]]
[21:39:35] [Server thread/INFO]: onPacketSending: PacketContainer[type=ENTITY_VELOCITY[class=PacketPlayOutEntityVelocity, id=84], structureModifier=StructureModifier[fieldType=class java.lang.Object, data=[com.comphenix.protocol.reflect.accessors.DefaultFieldAccessor@6b234365, com.comphenix.protocol.reflect.accessors.DefaultFieldAccessor@5df939cb, com.comphenix.protocol.reflect.accessors.DefaultFieldAccessor@3025c51b, com.comphenix.protocol.reflect.accessors.DefaultFieldAccessor@bd20b]]]
[21:39:35] [Server thread/INFO]: onPacketSending: PacketContainer[type=ENTITY_TELEPORT[class=PacketPlayOutEntityTeleport, id=104], structureModifier=StructureModifier[fieldType=class java.lang.Object, data=[com.comphenix.protocol.reflect.accessors.DefaultFieldAccessor@2537cbd3, com.comphenix.protocol.reflect.accessors.DefaultFieldAccessor@401834c0, com.comphenix.protocol.reflect.accessors.DefaultFieldAccessor@2bde682c, com.comphenix.protocol.reflect.accessors.DefaultFieldAccessor@46e8034e, com.comphenix.protocol.reflect.accessors.DefaultFieldAccessor@5d1a2113, com.comphenix.protocol.reflect.accessors.DefaultFieldAccessor@5c25a044, com.comphenix.protocol.reflect.accessors.DefaultFieldAccessor@4e22ce4]]]
[21:39:35] [Server thread/INFO]: onPacketSending: PacketContainer[type=UPDATE_ATTRIBUTES[class=PacketPlayOutUpdateAttributes, id=106], structureModifier=StructureModifier[fieldType=class java.lang.Object, data=[com.comphenix.protocol.reflect.accessors.DefaultFieldAccessor@267203c1, com.comphenix.protocol.reflect.accessors.DefaultFieldAccessor@6dc00e29]]]
[21:39:35] [Netty Epoll Server IO #1/INFO]: onPacketReceiving: PacketContainer[type=POSITION[class=PacketPlayInPosition, id=20], structureModifier=StructureModifier[fieldType=class java.lang.Object, data=[com.comphenix.protocol.reflect.accessors.DefaultFieldAccessor@22853e97, com.comphenix.protocol.reflect.accessors.DefaultFieldAccessor@e194416, com.comphenix.protocol.reflect.accessors.DefaultFieldAccessor@20c6d1fc, com.comphenix.protocol.reflect.accessors.DefaultFieldAccessor@3d2a4175, com.comphenix.protocol.reflect.accessors.DefaultFieldAccessor@36d0a1c1, com.comphenix.protocol.reflect.accessors.DefaultFieldAccessor@722d6af9, com.comphenix.protocol.reflect.accessors.DefaultFieldAccessor@64f20c71, com.comphenix.protocol.reflect.accessors.DefaultFieldAccessor@b3cc873]]]
[21:39:36] [Server thread/INFO]: onPacketSending: PacketContainer[type=UPDATE_TIME[class=PacketPlayOutUpdateTime, id=94], structureModifier=StructureModifier[fieldType=class java.lang.Object, data=[com.comphenix.protocol.reflect.accessors.DefaultFieldAccessor@1515d6b8, com.comphenix.protocol.reflect.accessors.DefaultFieldAccessor@2f84bbd0]]]
[21:39:37] [Server thread/INFO]: onPacketSending: PacketContainer[type=UPDATE_TIME[class=PacketPlayOutUpdateTime, id=94], structureModifier=StructureModifier[fieldType=class java.lang.Object, data=[com.comphenix.protocol.reflect.accessors.DefaultFieldAccessor@1515d6b8, com.comphenix.protocol.reflect.accessors.DefaultFieldAccessor@2f84bbd0]]]
[21:39:37] [Server thread/INFO]: onPacketSending: PacketContainer[type=NAMED_SOUND_EFFECT[class=PacketPlayOutNamedSoundEffect, id=98], structureModifier=StructureModifier[fieldType=class java.lang.Object, data=[com.comphenix.protocol.reflect.accessors.DefaultFieldAccessor@296bd45, com.comphenix.protocol.reflect.accessors.DefaultFieldAccessor@e0816bd, com.comphenix.protocol.reflect.accessors.DefaultFieldAccessor@7fdea0b8, com.comphenix.protocol.reflect.accessors.DefaultFieldAccessor@6ace26ab, com.comphenix.protocol.reflect.accessors.DefaultFieldAccessor@5d05d222, com.comphenix.protocol.reflect.accessors.DefaultFieldAccessor@13769ac1, com.comphenix.protocol.reflect.accessors.DefaultFieldAccessor@19273377, com.comphenix.protocol.reflect.accessors.DefaultFieldAccessor@247b586]]]
[21:39:38] [Server thread/INFO]: onPacketSending: PacketContainer[type=UPDATE_TIME[class=PacketPlayOutUpdateTime, id=94], structureModifier=StructureModifier[fieldType=class java.lang.Object, data=[com.comphenix.protocol.reflect.accessors.DefaultFieldAccessor@1515d6b8, com.comphenix.protocol.reflect.accessors.DefaultFieldAccessor@2f84bbd0]]]
[21:39:38] [Server thread/INFO]: onPacketSending: PacketContainer[type=REL_ENTITY_MOVE[class=PacketPlayOutRelEntityMove, id=43], structureModifier=StructureModifier[fieldType=class java.lang.Object, data=[com.comphenix.protocol.reflect.accessors.DefaultFieldAccessor@6ae4ebe9, com.comphenix.protocol.reflect.accessors.DefaultFieldAccessor@25bb20d0, com.comphenix.protocol.reflect.accessors.DefaultFieldAccessor@1f0e8500, com.comphenix.protocol.reflect.accessors.DefaultFieldAccessor@16dad329, com.comphenix.protocol.reflect.accessors.DefaultFieldAccessor@5bacc9b8, com.comphenix.protocol.reflect.accessors.DefaultFieldAccessor@27edcfbd, com.comphenix.protocol.reflect.accessors.DefaultFieldAccessor@4c2068c5, com.comphenix.protocol.reflect.accessors.DefaultFieldAccessor@ca3a9f3, com.comphenix.protocol.reflect.accessors.DefaultFieldAccessor@31ff40d6]]]
```

File: src/main/java/com/comphenix/protocol/PacketType.java [hunk 2]
```diff
@@ -102,113 +102,117 @@ public static class Play {
...
-			public static final PacketType ENTITY_TELEPORT =              new PacketType(PROTOCOL, SENDER, 0x64, "EntityTeleport", "SPacketEntityTeleport");
-			public static final PacketType ADVANCEMENTS =                 new PacketType(PROTOCOL, SENDER, 0x65, "Advancements", "SPacketAdvancementInfo");
-			public static final PacketType UPDATE_ATTRIBUTES =            new PacketType(PROTOCOL, SENDER, 0x66, "UpdateAttributes", "SPacketEntityProperties");
-			public static final PacketType UPDATE_ENABLED_FEATURES =      new PacketType(PROTOCOL, SENDER, 0x67, "UpdateEnabledFeatures");
-			public static final PacketType ENTITY_EFFECT =                new PacketType(PROTOCOL, SENDER, 0x68, "EntityEffect", "SPacketEntityEffect");
-			public static final PacketType RECIPE_UPDATE =                new PacketType(PROTOCOL, SENDER, 0x69, "RecipeUpdate");
-			public static final PacketType TAGS =                         new PacketType(PROTOCOL, SENDER, 0x6A, "Tags");
+			public static final PacketType BUNDLE_DELIMITER =             new PacketType(PROTOCOL, SENDER, 0x00, "BundleDelimiterPacket");
```
Comment (romanalexander) [inline src/main/java/com/comphenix/protocol/PacketType.java:105]: I believe this should be

public static final PacketType BUNDLE_DELIMITER =             new PacketType(PROTOCOL, SENDER, 0x00, "BundleDelimiter"); or it won't get the class name correctly.

File: src/main/java/com/comphenix/protocol/PacketType.java [hunk 3]
```diff
@@ -102,113 +102,117 @@ public static class Play {
...
+			public static final PacketType BLOCK_CHANGED_ACK =            new PacketType(PROTOCOL, SENDER, 0x06, "BlockChangedAck");
+			public static final PacketType BLOCK_BREAK_ANIMATION =        new PacketType(PROTOCOL, SENDER, 0x07, "BlockBreakAnimation", "SPacketBlockBreakAnim");
+			public static final PacketType TILE_ENTITY_DATA =             new PacketType(PROTOCOL, SENDER, 0x08, "TileEntityData", "SPacketUpdateTileEntity");
+			public static final PacketType BLOCK_ACTION =                 new PacketType(PROTOCOL, SENDER, 0x09, "BlockAction", "SPacketBlockAction");
+			public static final PacketType BLOCK_CHANGE =                 new PacketType(PROTOCOL, SENDER, 0x0A, "BlockChange", "SPacketBlockChange");
+			public static final PacketType BOSS =                         new PacketType(PROTOCOL, SENDER, 0x0B, "Boss", "SPacketUpdateBossInfo");
+			public static final PacketType SERVER_DIFFICULTY =            new PacketType(PROTOCOL, SENDER, 0x0C, "ServerDifficulty", "SPacketServerDifficulty");
+			public static final PacketType CHUNKS_BIOMES =                new PacketType(PROTOCOL, SENDER, 0x0D, "ChunksBiomes");
```
Comment (kennytv) [inline src/main/java/com/comphenix/protocol/PacketType.java:118]: ChunkBiomes, not ChunksBiomes

File: src/main/java/com/comphenix/protocol/PacketType.java (hunk 2 above)
Comment (kennytv) [reply src/main/java/com/comphenix/protocol/PacketType.java:105]: Bundle, not BundleDelimiter/BundleDelimiterPacket

**Review by kennytv — CHANGES_REQUESTED** [review]

File: src/main/java/com/comphenix/protocol/PacketType.java (hunk 3 above)
Comment (dawon) [reply src/main/java/com/comphenix/protocol/PacketType.java:118]: The Class is named ClientboundChunksBiomesPacket, so should it really be ChunkBiomes?

Comment (kennytv) [reply src/main/java/com/comphenix/protocol/PacketType.java:118]: Oh sorry, misread and swapped that around in my head

**Comment by Brokkonaut** [comment]
Listeners for ENTITY_EQUIPMENT do not work in this PR, when the entity is loaded with equipment. Probably because it is bundled (same as SPAWN_ENTITY)

**Comment by derklaro** [comment]
Just move the ProtocolLib packet listener in front of the bundle handler 🤷

**Comment by dawon** [comment]
I am sorry for the long delay and no answer, last week I did not get my PC at all and had basically zero free time. From what I see 1.19.4 update was already pushed by dmulloy, so I will close this PR.

**Comment by molor** [comment]
At least you can try to make it work correctly with server ping packet..
